### ISSUE TITLE
Output audio sounds bad

### ISSUE THREAD

**Issue by kdwk** [gianni-rosato/aviator#16]
With Aviator I get very bad-sounding audio in the output file, but with `ffmpeg -i "infile.mkv" -c:v libsvtav1 -c:a libopus -preset n -crf n "outfile.mkv"` in the command line the output audio sounds fine.

**Comment by Amateurintheflesh** [comment]
Does this happen regardless of the bitrate you set the audio to be in Aviator? & is it worse when bitrate is set the to the same value through ffmpeg as in Aviator?

**Comment by kdwk** [comment]
I use “same as source” for Aviator, and the audio sounds bad regardless of the ‘variable but rate’ setting. I don’t set a bit rate in ffmpeg and just let it do its thing.

**Comment by kdwk** [comment]
For comparison,
this is the original audio: 
[original audio.zip](https://github.com/natesales/aviator/files/9926808/original.audio.zip) (contains a .aac file)

this is the Aviator-converted audio:
[aviator converted audio.zip](https://github.com/natesales/aviator/files/9926816/aviator.converted.audio.zip) (contains a .opus file)

and this is the ffmpeg-converted audio:
[ffmpeg converted audio.zip](https://github.com/natesales/aviator/files/9926827/ffmpeg.converted.audio.zip) (contains a .opus file)

In the 'Audio' tab of Aviator, bitrate is set to 48kbps, with variable refresh rate turned on.
For ffmpeg, the complete command is `ffmpeg -i "orginal video.mkv" -c:v libsvtav1 -preset 6 -crf 32 -c:a libopus "ffmpeg converted video.mkv` (I then extracted the audio)

The original video file has two audio tracks, one stereo and one 5.1. The stereo track has a human voice on top of the soundtrack. After Aviator's conversion, the stereo track sounds fine but the 5.1 one sounds bad. After ffmpeg's conversion, both tracks sound fine. I removed the stereo track in all of the included audio files.

**Comment by Amateurintheflesh** [comment]
Currently we’re having problems with dual audio streams, so if your video file has two audio streams attached there’s a chance that’s the culprit. I will look into this more, thanks for bringing it up!

**Comment by Amateurintheflesh** [comment]
The problem is definitely a bitrate problem. We're currently having trouble detecting the source bitrate for audio in Aviator, and the bitrate is being set to 48kbps by default. Your audio track reencoded with ffmpeg is actually 3mb, while Aviator's audio is a little under 400kb, so there's definitely a bitrate issue here. Let me know what happens if you set an equivalent bitrate in ffmpeg as you do in Aviator (say, 64kbps) & if that causes any problems. Thank you again.

**Comment by gianni-rosato** [comment]
user error, can't reproduce
