### ISSUE TITLE
Subjective Mode Flag

### ISSUE THREAD

**Issue by gianni-rosato** [gianni-rosato/aviator#20]
“The use of subjective mode (--tune=0) often results in an image with greater
sharpness and is intended to produce a result that appears to humans
to be of high quality (as opposed to doing well on basic objective measures, such as
PSNR).”

**Comment by Amateurintheflesh** [comment]
An update, this can be done with `-svtav1-params tune=0` after `-preset` flag

**Comment by gianni-rosato** [comment]
irrelevant - moving to rav1e
