### ISSUE TITLE
Options for audio filters

### ISSUE THREAD

**Issue by lastrosade** [gianni-rosato/aviator#25]
It would be useful to be able to use the [loudnorm](https://ffmpeg.org/ffmpeg-all.html#loudnorm), [volume](https://ffmpeg.org/ffmpeg-filters.html#volume) or [adeclick](https://ffmpeg.org/ffmpeg-filters.html#toc-adeclick) filters.

Some audio tracks tend to be unnecessarily loud or badly compressed.

**Comment by gianni-rosato** [comment]
89ced0a76f94af9bce88eed44e4e45ad333b9e21
