### ISSUE TITLE
10-bit encoding option

### ISSUE THREAD

**Issue by kdwk** [gianni-rosato/aviator#28]
SVT-AV1 allows encoding videos in 10-bit with minimal encoding time and file size penalty, resulting in reduced color banding artifacts in low-light scenes.

I propose that Aviator include a toggle with the label '10-bit'.

**Comment by gianni-rosato** [comment]
10-bit is enabled by default because of the reasons you listed. `"-pix_fmt", "yuv420p10le",`

You can check src/__init.py__ for our full list of encoding parameters

**Comment by kdwk** [comment]
Ah, I didn't realize that. Thanks.
