### ISSUE TITLE
Spinner doesn’t spin

### ISSUE THREAD

**Issue by kdwk** [gianni-rosato/aviator#30]
There’s a spinner to indicate activity in the export tab, but that doesn’t spin.

**Comment by gianni-rosato** [comment]
Try clicking it when it stops spinning. This is a libadwaita issue that we are currently not sure how to solve.

**Comment by kdwk** [comment]
> Try clicking it when it stops spinning. This is a libadwaita issue that we are currently not sure how to solve.

Oh wow that worked. Maybe I should file a libadwaita issue?

**Comment by gianni-rosato** [comment]
If you do, link it to me & I'll keep an eye on it. I've had the same issue in a multitude of other apps
