### ISSUE TITLE
New update broke the app

### ISSUE THREAD

**Issue by Sabering1** [gianni-rosato/aviator#32]
After the latest update the app is now broken
Downloaded from flathub a few days ago
It used to work fine
bun now it wont encode anything

**Comment by gianni-rosato** [comment]
Hi, I'm aware of the issue & a hotfix is en route with version 0.2.1a - apologies for the issue & I appreciate your patience! In the meantime, encoding as a WebM should work for version 0.2.1

**Comment by gianni-rosato** [comment]
9bdabec71d39c1dd0b89cd6ed268e458fe97a915

**Comment by Sabering1** [comment]
yea its fixed now, good job
