### ISSUE TITLE
Use flatpak-cargo-generator in rAV1ator flatpak

### ISSUE THREAD

**Issue by konradmb** [gianni-rosato/aviator#34]
> Flathub doesn't allow us to use the network at build time to build our dependencies, which makes it impossible to build our app.

Have you tried using https://github.com/flatpak/flatpak-builder-tools/tree/master/cargo to generate jsons for dependencies? You won't need network permission then.

**Comment by gianni-rosato** [comment]
Yes, this has already been tried, & it doesn't work. It generates jsons of dependencies that are either too new or too old for rAV1ator to function properly.
