### ISSUE TITLE
Option to convert HDR -> SDR

### ISSUE THREAD

**Issue by kdwk** [gianni-rosato/aviator#35]
It would be handy to have an option to add a BT.709 colorspace filter to the video during conversion such that HDR content can be converted to SDR and be displayed properly in Linux apps.

**Comment by kdwk** [comment]
![image](https://user-images.githubusercontent.com/39268094/224489812-a88700f3-e00e-48b7-a356-e802386e04d0.png)

**Comment by BlueSwordM** [comment]
? I can watch HDR content just fine on my Linux system with mpv and VLC...

**Comment by gianni-rosato** [comment]
Like Blue said, I think the best way to tonemap HDR content is with your player on Linux. Also, our goal is not feature parity with Handbrake, so I don't understand the screenshot. Personally I don't want to give beginners the impression that reencoding is the only way to watch anything in SDR
