### ISSUE TITLE
Many videos fail to encode silently

### ISSUE THREAD

**Issue by kdwk** [gianni-rosato/aviator#41]
Many videos fail to start encoding without any error message. They just get stuck at 0% indefinitely after making an empty file with the requested filename. However, Handbrake can encode them in AV1/opus.

**Comment by gianni-rosato** [comment]
Can you provide some samples? Thanks

**Comment by kdwk** [comment]
You can try this one: http://kdwk.tplinkdns.com/index.php/s/7q947J84LPisCNz

It's an H.265/E-AC-3 video

**Comment by gianni-rosato** [comment]
If you flip the "Downmix to Stereo" switch in the Audio tab, does it then work?

**Comment by kdwk** [comment]
It does work after that

**Comment by gianni-rosato** [comment]
can't repro
