### ISSUE TITLE
Feature: Hardware transcoding

### ISSUE THREAD

**Issue by TriVoxel** [gianni-rosato/aviator#45]
Some GPU's such as my AMD Radeon 7900XTX should have AV1 hardware encoding support, as well as decoding for other formats. This could speed up transcodes considerably if you could get this working! Maybe as a preference? I think newer Intel CPUs and GPUs support AV1 in hardware, as well...

**Comment by JND94** [comment]
> Maybe as a preference?
Never. Hardware encoding is shit, AMD hardware encoding is even shittier

**Comment by TriVoxel** [comment]
> > Maybe as a preference?
> 
> Never. Hardware encoding is shit > AMD hardware encoding is even shittier > AMD vaapi encoding is the bigger pile of shit out there

Perhaps consider using Jellyfin's FFMPEG fork. It's very good in my experience. It handles transcoding very seamlessly and I've had good experience with it. MUCH faster than software, at least for X265...

**Comment by 190n** [comment]
I suspect @JND94's complaint is regarding efficiency (quality per bitrate), not speed. The tradeoff for speed is that you get worse quality at the same bitrate, or need a higher bitrate for the same quality, than a software encoder.

**Comment by TriVoxel** [comment]
> I suspect @JND94's complaint is regarding efficiency (quality per bitrate), not speed. The tradeoff for speed is that you get worse quality at the same bitrate, or need a higher bitrate for the same quality, than a software encoder.

I mean, that is fair, but honestly, sometimes you just want speed for certain things. I get it though. Again, though, Jellyfin did a fantastic job with their fork, and I highly recommend we check it out because their GPU transcoding is fast, stable, reliable, and seems to look pretty good as well. Better than stock anyways...

**Comment by JND94** [comment]
> Perhaps consider using Jellyfin's FFMPEG fork. It's very good in my experience. It handles transcoding very seamlessly and I've had good experience with it. MUCH faster than software, at least for X265...

You mean H265/HEVC, x265 is an encoder. And you're talking about realtime encoding.
aviator is intended for efficient encoding and not realtime, software encoding is the only way to achieve this, speed doesn't matter here, if you want speed you have alternatives.

And you don't need any fork of ffmpeg to use hardware encoding.

**Comment by gianni-rosato** [comment]
This isn't in scope. Aviator is **A lightweight, Flatpak-first, easy-to-use GUI utility for encoding with SVT-AV1 & Opus.**

Expanding on this a bit, Aviator is a utility for encoding with SVT-AV1 & Opus as efficiently as possible, focused solely on extracting maximum perceptual quality per bit in the medium fidelity range out of any given source video. Other encoders are not in scope. I have a command line tool called [rAV1ator CLI](https://github.com/gianni-rosato/rav1ator-cli/) that is focused on such things.
