### ISSUE TITLE
Feature: Audio codec selection

### ISSUE THREAD

**Issue by TriVoxel** [gianni-rosato/aviator#48]
Please allow user to choose the audio codec, for example, AAC, OPUS, MP3, OGG... This could be very useful.

_Additionally, some information about the surround sound of the source file would be useful, ie. stereo, 5.1, 7.1, if at all possible..._

**Comment by gianni-rosato** [comment]
This isn't in scope. Aviator is **A lightweight, Flatpak-first, easy-to-use GUI utility for encoding with SVT-AV1 & Opus.**

Expanding on this a bit, Aviator is a utility for encoding with SVT-AV1 & libopus (opusenc) as efficiently as possible, focused solely on extracting maximum perceptual quality per bit in the medium fidelity range out of any given source video. Other encoders are not in scope. I have a command line tool called [rAV1ator CLI](https://github.com/gianni-rosato/rav1ator-cli/) that is focused on such things.

If you want source info, use MediaInfo. It will always be better than Aviator for source information.
