### ISSUE TITLE
Feature: Video codec selection

### ISSUE THREAD

**Issue by TriVoxel** [gianni-rosato/aviator#49]
Since this app is basically a wrapper for FFMPEG, would be nice if the user could choose other video codecs such as X264, X265, and AV1. Perhaps a better name would be "Mediator" if you went this route?

**Comment by gianni-rosato** [comment]
This isn't in scope. You're admitting this by proposing it become an entirely new application. Aviator is **A lightweight, Flatpak-first, easy-to-use GUI utility for encoding with SVT-AV1 & Opus.**

Expanding on this a bit, Aviator is a utility for encoding with SVT-AV1 & libopus (opusenc) as efficiently as possible, focused solely on extracting maximum perceptual quality per bit in the medium fidelity range out of any given source video. Other encoders are not in scope. I have a command line tool called [rAV1ator CLI](https://github.com/gianni-rosato/rav1ator-cli/) that is focused on such things.

**Comment by TriVoxel** [comment]
> This isn't in scope. You're admitting this by proposing it become an entirely new application. Aviator is **A lightweight, Flatpak-first, easy-to-use GUI utility for encoding with SVT-AV1 & Opus.**
> 
> Expanding on this a bit, Aviator is a utility for encoding with SVT-AV1 & libopus (opusenc) as efficiently as possible, focused solely on extracting maximum perceptual quality per bit in the medium fidelity range out of any given source video. Other encoders are not in scope. I have a command line tool called [rAV1ator CLI](https://github.com/gianni-rosato/rav1ator-cli/) that is focused on such things.

Good to know. I figured it might be. I will still contribute to this app. After I've contributed, I think I might fork it, as I have a vision for a similar app, but with a bit more flexibility in terms of codecs and features! Basically, the GTK Handbrake of sorts...

**Comment by gianni-rosato** [comment]
Sounds like a great idea! If you'd like any help with that, I'd be happy to consult on encoder defaults
