### ISSUE TITLE
Feature: VBR option

### ISSUE THREAD

**Issue by TriVoxel** [gianni-rosato/aviator#50]
Variable Bit Rate (VBR) is useful as it can save on filesize compared to CRF. Please add an option to toggle between CRF and VRF in the video panel.

**Comment by gianni-rosato** [comment]
Compared to CRF, VBR won't always use the optimal amount of bits for each frame. I understand this provides the user with more flexibility, but Aviator is designed to be efficient-only, sometimes at the cost of flexibility. Closing, this is out of scope.
