### ISSUE TITLE
[request] add command line parameters

### ISSUE THREAD

**Issue by AndreaMonzini** [gianni-rosato/aviator#60]
I think that Aviator is a great project to learn and test AV1 econding.

I know that i can see the parameters if i run Aviator from the command line but adding the command line parameters in the export tab could be useful as learning tool.

thank you

**Comment by gianni-rosato** [comment]
Thanks for the request. I don't think this is really within the scope of Aviator's design goals, but my other tool [rAV1ator CLI](https://wiki.x266.mov/docs/utilities/rav1ator-cli) might be of interest to you :)
