### ISSUE TITLE
Support Deinterlacing

### ISSUE THREAD

**Issue by prismfuzz** [gianni-rosato/aviator#66]
Love Aviator so much all it needs for me to let go of Handbrake (a cool tool that has so many features i don't need) is the ability to deinterlace. I got a bunch of 480i movies and cartoons and a few old family videos i want to encode

**Comment by gianni-rosato** [comment]
Hey, thanks for the suggestion!

This shouldn't be too difficult to implement, so I'll look into it for the next version of Aviator. Keep an eye on the release notes in the meantime!

**Comment by gianni-rosato** [comment]
fd6280f7e495634413d0f2b0e90e3a1d428b346e
